# Домашнее задание к занятию "Классификация: Логистическая регрессия и SVM"

In [1]:
import numpy as np
import pandas as pd 
import scipy.stats
import matplotlib.pyplot as plt 

In [2]:
data = pd.read_csv('adult.csv')
data.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18          ?  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                  ?    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              48842 non-null  int64 
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64 
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64 
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64 
 11  capital-loss     48842 non-null  int64 
 12  hours-per-week   48842 non-null  int64 
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB


In [4]:
from sklearn.linear_model import LogisticRegression

In [6]:
data['income'].unique() # отклик содержит только два варинта: бинарная классификация, используем для кодирования LabelEncoder()

array(['<=50K', '>50K'], dtype=object)

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [8]:
le.fit( data['income'])

LabelEncoder()

In [9]:
Y = pd.Series( data = le.transform(data['income']))
Y.head()

0    0
1    0
2    1
3    1
4    0
dtype: int32

#### Проведем отбор категориальных признаков, которые необходимо перекодировать

In [10]:
selectedColumns = data[['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'gender','native-country']]

In [11]:
X = pd.get_dummies (selectedColumns, columns = ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'gender','native-country'])

In [12]:
X.head()

workclass_?  workclass_Federal-gov  workclass_Local-gov  \
0            0                      0                    0   
1            0                      0                    0   
2            0                      0                    1   
3            0                      0                    0   
4            1                      0                    0   

   workclass_Never-worked  workclass_Private  workclass_Self-emp-inc  \
0                       0                  1                       0   
1                       0                  1                       0   
2                       0                  0                       0   
3                       0                  1                       0   
4                       0                  0                       0   

   workclass_Self-emp-not-inc  workclass_State-gov  workclass_Without-pay  \
0                           0                    0                      0   
1                           0                    0                      0   
2                           0                    0                      0   
3                           0                    0                      0   
4                           0                    0                      0   

   education_10th  ...  native-country_Portugal  native-country_Puerto-Rico  \
0               0  ...                        0                           0   
1               0  ...                        0                           0   
2               0  ...                        0                           0   
3               0  ...                        0                           0   
4               0  ...                        0                           0   

   native-country_Scotland  native-country_South  native-country_Taiwan  \
0                        0                     0                      0   
1                        0                     0                      0   
2                        0                     0                      0   
3                        0                     0                      0   
4                        0                     0                      0   

   native-country_Thailand  native-country_Trinadad&Tobago  \
0                        0                               0   
1                        0                               0   
2                        0                               0   
3                        0                               0   
4                        0                               0   

   native-country_United-States  native-country_Vietnam  \
0                             1                       0   
1                             1                       0   
2                             1                       0   
3                             1                       0   
4                             1                       0   

   native-country_Yugoslavia  
0                          0  
1                          0  
2                          0  
3                          0  
4                          0  

[5 rows x 102 columns]

#### Алгоритм логистической регрессии

In [13]:
from sklearn.pipeline import make_pipeline 
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split 

model = make_pipeline(StandardScaler(), LogisticRegression(max_iter=1000))

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=2021)

In [15]:
model.fit(X_train, y_train)
predictions = model.predict(X_test)

In [16]:
predictions[:5]

array([0, 0, 1, 1, 0])

In [17]:
model.predict(X_test)

array([0, 0, 1, ..., 0, 0, 0])

In [18]:
model.predict_proba(X_test)

array([[0.99721062, 0.00278938],
       [0.97830011, 0.02169989],
       [0.39448345, 0.60551655],
       ...,
       [0.98725991, 0.01274009],
       [0.99163208, 0.00836792],
       [0.98383732, 0.01616268]])

In [19]:
model.score(X_test,y_test)

0.831911553947997

## SVM

In [20]:
from sklearn.svm import SVC
clf = make_pipeline(StandardScaler(), SVC(gamma='auto')) 
clf.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(gamma='auto'))])

In [21]:
clf.score(X_test, y_test)

0.8302054186855934