In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets

In [215]:
iris = datasets.load_iris()

In [216]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [217]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [218]:
# отберем только цветки 'versicolor' и 'verginica'
X = iris.data[50:]
Y = iris.target[50:]

In [219]:
# сделаем перекодировку значений с 1 и 2 на 0 и 1
for i in range(0,len(Y)):
    if Y[i] == 1:
        Y[i] = 0
print(Y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [220]:
for i in range(0,len(Y)):
    if Y[i] == 2:
        Y[i] = 1
print(Y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [221]:
len(Y)

100

In [222]:
# определим начальные коэффициенты регрессии
tetta = np.random.normal(size=(5,))
tetta

array([ 0.35941926, -0.02994615,  1.39640714, -1.25529712, -0.32726811])

In [223]:
# Определим матрицу X, добавив в нее столбец из единиц, для умножения на тетта 0
X = np.c_[X, np.ones(X.shape[0])] 
X

array([[7. , 3.2, 4.7, 1.4, 1. ],
       [6.4, 3.2, 4.5, 1.5, 1. ],
       [6.9, 3.1, 4.9, 1.5, 1. ],
       [5.5, 2.3, 4. , 1.3, 1. ],
       [6.5, 2.8, 4.6, 1.5, 1. ],
       [5.7, 2.8, 4.5, 1.3, 1. ],
       [6.3, 3.3, 4.7, 1.6, 1. ],
       [4.9, 2.4, 3.3, 1. , 1. ],
       [6.6, 2.9, 4.6, 1.3, 1. ],
       [5.2, 2.7, 3.9, 1.4, 1. ],
       [5. , 2. , 3.5, 1. , 1. ],
       [5.9, 3. , 4.2, 1.5, 1. ],
       [6. , 2.2, 4. , 1. , 1. ],
       [6.1, 2.9, 4.7, 1.4, 1. ],
       [5.6, 2.9, 3.6, 1.3, 1. ],
       [6.7, 3.1, 4.4, 1.4, 1. ],
       [5.6, 3. , 4.5, 1.5, 1. ],
       [5.8, 2.7, 4.1, 1. , 1. ],
       [6.2, 2.2, 4.5, 1.5, 1. ],
       [5.6, 2.5, 3.9, 1.1, 1. ],
       [5.9, 3.2, 4.8, 1.8, 1. ],
       [6.1, 2.8, 4. , 1.3, 1. ],
       [6.3, 2.5, 4.9, 1.5, 1. ],
       [6.1, 2.8, 4.7, 1.2, 1. ],
       [6.4, 2.9, 4.3, 1.3, 1. ],
       [6.6, 3. , 4.4, 1.4, 1. ],
       [6.8, 2.8, 4.8, 1.4, 1. ],
       [6.7, 3. , 5. , 1.7, 1. ],
       [6. , 2.9, 4.5, 1.5, 1. ],
       [5.7, 2

In [224]:
def lin_reg(x1, x2, x3, x4, x5, t1, t2, t3, t4, t5 ):
    predict = x1*t1 + x2*t2 + x3*t3 + x4*t4 + x5*t5  
    p = 1. / (1 + np.exp(-predict))
    return p

In [225]:
P = lin_reg(X[:,4], X[:,0], X[:,1], X[:,2], X[:,3], tetta[0], tetta[1], tetta[2], tetta[3], tetta[4])  
P

array([0.1493418 , 0.18190819, 0.10338144, 0.11504788, 0.10060145,
       0.12178659, 0.16183694, 0.28788295, 0.12041989, 0.20103541,
       0.15208959, 0.19921758, 0.10942592, 0.1060496 , 0.33109944,
       0.18334599, 0.14694108, 0.17976279, 0.05245641, 0.17180123,
       0.12311371, 0.20424855, 0.04833387, 0.0992192 , 0.16716119,
       0.16376371, 0.08181967, 0.07692782, 0.12893411, 0.28875811,
       0.17022529, 0.19375786, 0.20877097, 0.04854031, 0.14769341,
       0.22357739, 0.12975165, 0.07134163, 0.23304001, 0.14667719,
       0.11000842, 0.13393876, 0.16832851, 0.25954713, 0.14986295,
       0.21635729, 0.18856071, 0.16799667, 0.39456232, 0.18641113,
       0.02735683, 0.04445545, 0.02280976, 0.03234528, 0.02541376,
       0.00946004, 0.07575366, 0.01329397, 0.01448561, 0.03541338,
       0.08141466, 0.03432939, 0.03745681, 0.037281  , 0.0434473 ,
       0.0589934 , 0.04151791, 0.02423794, 0.00348855, 0.02887302,
       0.03603318, 0.06274766, 0.00652056, 0.05737928, 0.04412

In [226]:
def cross_entropy(Y, S):

    E = 0

    for i in range(len(P)):
        if Y[i] ==1:
            E -= np.log(S[i])
        else:
            E -= np.log(1 - S[i])
    return E

### Градиентный спуск

In [227]:
K = []
for i in range(0,len(Y)):
    K.append(Y[i])
print(K)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [228]:
Y = K

In [251]:
learning_rate = 0.0001
# выбираем начальное приближение
tetta = [-0.1960596 , -0.30755035,  0.38426438,  0.68284465, -0.41863886]
for i in range(100):
    if i % 10 ==0:
        f = lin_reg(X[:,4], X[:,0], X[:,1], X[:,2], X[:,3], tetta[0], tetta[1], tetta[2], tetta[3], tetta[4])
        tetta[0] -= learning_rate * np.sum((f - Y) * X[:, 4])/len(f)
        tetta[1] -= learning_rate * np.sum((f - Y) * X[:, 0])/len(f)
        tetta[2] -= learning_rate * np.sum((f - Y) * X[:, 1])/len(f)
        tetta[3] -= learning_rate * np.sum((f - Y) * X[:, 2])/len(f)
        tetta[4] -= learning_rate * np.sum((f - Y) * X[:, 3])/len(f)
        print(cross_entropy(Y, f))
        print(tetta)

88.49615788882156
[-0.19609270322634056, -0.3077433544378112, 0.38417345646912804, 0.6827110347294454, -0.4186782451825816]
88.4301732552887
[-0.1961257763278832, -0.3079361709959426, 0.3840826188933842, 0.6825775649111268, -0.41871758067475884]
88.36432146865778
[-0.19615881929130594, -0.3081287995857626, 0.38399186731303064, 0.682444240617576, -0.4187568664511233]
88.29860245797778
[-0.19619183210340782, -0.30832124011939627, 0.38390120176798387, 0.6823110619207396, -0.4187961024864673]
88.23301615157
[-0.1962248147511089, -0.308513492509726, 0.38381062229781404, 0.6821780288919778, -0.41883528875578424]
88.16756247703043
[-0.19625776722145044, -0.3087055566703925, 0.3837201289417449, 0.6820451416020636, -0.41887442523426854]
88.10224136123034
[-0.19629068950159498, -0.30889743251579554, 0.3836297217386531, 0.6819124001211833, -0.4189135118973163]
88.03705273031863
[-0.19632358157882648, -0.30908911996109456, 0.3835394007270683, 0.6817798045189342, -0.4189525487205251]
87.97199650972

### Nesterov Momentum

In [238]:
gamma = 0.9
learning_rate = 0.0001
n = 0.05
v = np.array([0 for i in range(5)])
tetta = np.array([-0.1960596 , -0.30755035,  0.38426438,  0.68284465, -0.41863886])
for i in range(100):
    if i % 10 ==0:
        f = lin_reg(X[:,4], X[:,0], X[:,1], X[:,2], X[:,3], tetta[0], tetta[1], tetta[2], tetta[3], tetta[4])
        tetta[0] -= (gamma*v[0] + learning_rate * np.sum((f - Y) * X[:, 4]))/len(f)
        tetta[1] -= (gamma*v[1] + learning_rate * np.sum((f - Y) * X[:, 0]))/len(f)
        tetta[2] -= (gamma*v[0] + learning_rate * np.sum((f - Y) * X[:, 1]))/len(f)
        tetta[3] -= (gamma*v[0] + learning_rate * np.sum((f - Y) * X[:, 2]))/len(f)
        tetta[4] -= (gamma*v[0] + learning_rate * np.sum((f - Y) * X[:, 3]))/len(f)
        print(tetta, cross_entropy(Y, f))

[-0.1960927  -0.30774335  0.38417346  0.68271103 -0.41867825] 88.49615788882156
[-0.19612578 -0.30793617  0.38408262  0.68257756 -0.41871758] 88.4301732552887
[-0.19615882 -0.3081288   0.38399187  0.68244424 -0.41875687] 88.36432146865778
[-0.19619183 -0.30832124  0.3839012   0.68231106 -0.4187961 ] 88.29860245797778
[-0.19622481 -0.30851349  0.38381062  0.68217803 -0.41883529] 88.23301615157
[-0.19625777 -0.30870556  0.38372013  0.68204514 -0.41887443] 88.16756247703043
[-0.19629069 -0.30889743  0.38362972  0.6819124  -0.41891351] 88.10224136123034
[-0.19632358 -0.30908912  0.3835394   0.6817798  -0.41895255] 88.03705273031863
[-0.19635644 -0.30928062  0.38344917  0.68164735 -0.41899154] 87.97199650972286
[-0.19638928 -0.30947193  0.38335902  0.68151505 -0.41903047] 87.9070726241506


### RMSProp

In [250]:
gamma = 0.9
learning_rate = 0.0001
eps = 0.00000001
v = np.array([0 for i in range(5)])
tetta = np.array([-0.1960596 , -0.30755035,  0.38426438,  0.68284465, -0.41863886])
for i in range(100):
    f = lin_reg(X[:,4], X[:,0], X[:,1], X[:,2], X[:,3], tetta[0], tetta[1], tetta[2], tetta[3], tetta[4])
    tetta[0] -= np.sum((f - Y) * X[:, 4])/len(f)
    tetta[1] -= np.sum((f - Y) * X[:, 0])/len(f)
    tetta[2] -= np.sum((f - Y) * X[:, 1])/len(f)
    tetta[3] -= np.sum((f - Y) * X[:, 2])/len(f)
    tetta[4] -= np.sum((f - Y) * X[:, 3])/len(f)
    v = gamma*v + (1-gamma)*tetta**2
    tetta = tetta - learning_rate * tetta/(np.sqrt(v+eps))
    print(tetta, cross_entropy(Y, f))

[-0.52677564 -2.2372785  -0.5246547  -0.65299183 -0.81217446] 88.49615788882156
[-0.02675874  1.05658053  0.96206443  2.12270458  0.2007458 ] 1104.8582787743374
[-0.52652388 -1.91121457 -0.42281518 -0.00729422 -0.46208915] 910.9466124529338
[-0.02651271  1.38263836  1.06395688  2.7684438   0.55073579] 767.5875251595538
[-0.5263116  -1.58521245 -0.32097344  0.63838257 -0.11222723] 1182.5919126914666
[-0.02658625  1.70697177  1.16504288  3.41283827  0.90010388] 430.3954712663914
[-0.52640381 -1.26091913 -0.21991689  1.28274961  0.2370433 ] 1453.2399928146026
[-0.12593904  1.40694318  0.9791803   3.54275427  1.06770178] 104.95815749853071
[-0.62574865 -1.56092953 -0.4057506   1.41267305  0.40461971] 1372.2935568595678
[-0.14983316  1.58301939  1.01188652  4.06379213  1.37290661] 175.10711338595797
[-0.64965417 -1.38487232 -0.37305339  1.93369899  0.70979668] 1559.2523977135702
[-0.70357603 -1.63046338 -0.50311149  1.81866906  0.70614398] 35.600368212632866
[-0.33501681  0.82559283  0.6009